name: 'Sync Feature Branches'
description: 'Syncs feature branches with the latest changes from the main branch'
author: 'Vadim Dvukhzhilov'
inputs:
  source_branch:
    required: true
    description: 'Name of the source branch'
    default: 'main'
  target_branch_regex:
    required: true
    description: 'A regexp for target branches'
    default: 'feature/.*'
runs:
  using: 'node18'
  main: 'dist/index.js'
