name: 'Sync Feature Branches'
description: 'Syncs feature branches with the latest changes from the main branch'
author: 'Vadim Dvukhzhilov'
inputs:
  github_token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  source_branch:
    required: true
    description: 'Name of the source branch'
    default: 'main'
  target_branch_ref:
    required: true
    description: 'A target branches ref'
    default: 'feature/'
runs:
  using: 'node18'
  main: 'dist/index.js'
