name: Verification

on:
  pull_request:
    paths-ignore:
      - '.vscode/**/*'
      - '*.md'
  push:
    branches:
      - main
      - 'releases/*'
    paths-ignore:
      - '.vscode/**/*'
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: magnetikonline/action-node-modules-cache@v1
        id: node-with-cache
        with:
          node-version: 18
          node-modules-path: node_modules
          package-lock-path: package-lock.json
      - name: Fetch and link dependencies
        run: npm install --no-audit --loglevel="error"
        if: steps.node-with-cache.outputs.cache-hit != 'true'
        shell: bash
      - name: Lint, test, build
        run: |
          npm run lint
          npm run test
          npm run build
  test-run:
    name: Make a test run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        uses: ./
        with:
          milliseconds: 500
